# Generated by Django 6.0.3 on 2026-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_mvp', '0002_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='received_by_trade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='delivery_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('hand', '🤝 Remise en main propre'), ('post', '📦 Via la poste'), ('other', '📋 Autre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('trade_received', 'Nouvel échange reçu'), ('trade_accepted', 'Échange accepté'), ('trade_refused', 'Échange refusé'), ('trade_cancelled', 'Échange annulé'), ('delivery_set', 'Mode de livraison défini'), ('delivery_confirmed', 'Livraison confirmée'), ('message_received', 'Nouveau message'), ('rating_received', 'Nouvelle notation')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté - En attente de confirmation livraison'), ('confirmed', 'Livraison confirmée'), ('completed', 'Terminé'), ('refused', 'Refusé'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
