# Generated by Django 6.0.3 on 2026-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_mvp', '0003_item_received_by_trade_trade_delivery_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('new', 'Neuf'), ('very_good', 'Très bon état'), ('good', 'Bon état'), ('correct', 'État correct'), ('damaged', 'Abîmé')], default='good', max_length=20, verbose_name='État'),
        ),
        migrations.AddField(
            model_name='item',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valeur estimée (€)'),
        ),
        migrations.AddField(
            model_name='item',
            name='platform',
            field=models.CharField(choices=[('ps5', 'PlayStation 5'), ('ps4', 'PlayStation 4'), ('xbox_series', 'Xbox Series'), ('xbox_one', 'Xbox One'), ('switch', 'Nintendo Switch'), ('pc', 'PC'), ('ps3', 'PlayStation 3'), ('wii', 'Wii / Wii U'), ('ds', 'Nintendo DS / 3DS'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Plateforme'),
        ),
        migrations.AddField(
            model_name='item',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de sortie'),
        ),
    ]
