[tool:pytest]
DJANGO_SETTINGS_MODULE = troc.settings
python_files = tests.py test_*.py *_tests.py
addopts = --tb=short --strict-markers
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
env =
    DJANGO_ALLOW_ASYNC_UNSAFE=1
markers =
    playwright: marks tests as Playwright tests (deselect with '-m "not playwright"')